language: node_js
node_js:
  - "0.10"
env:
  matrix:
  - DB_HOST=localhost DB_NAME=madison_grunt_test DB_USER=root ENV=testing
  global:
    secure: XPSHwPKz6T6gKRYD8gmBZI1TRU79VpE/puIdIzno3mcVfR9Mt0jR39r759EGOGX94rNo2vjoBlOHLvECSYKl6kn1gjuWQDq8LkOD2QGKO+KmE8GDaED4DFds6EvtoHm/pkFpVBsvjGucU6PEZo4ghxhQAGpuX112V5mj1qmf7g0=
    secure: eRHMypmB5JXiQXwa++FHjbNPg1LnLxJ97HTt/tcL4hrb9KTAioIg4vvOM07PaekLVkZnTtUnOUDDaOlkhSUzjUKaU+fnw4GcUvXTzj73efBSfkoSvWgkquiVCLV+8PJuYkske93ZcR5s91+4oPITQZ4IQVmviaUz3XdLFOgUUFk=
addons:
  sauce_connect: true
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install
- grunt install
script:
- grunt karma
- grunt protractor
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
